-- ============================================================================
-- CONFIGURAÇÃO DE POLÍTICAS RLS PARA O BUCKET DE AVATARES (avatars)
-- ============================================================================
-- IMPORTANTE: As políticas de Storage não podem ser criadas via SQL direto.
-- Use o Dashboard do Supabase para configurar as políticas.
--
-- PASSO A PASSO:
-- 1. Acesse: Supabase Dashboard > Storage > avatars > Policies
-- 2. Clique em "New Policy"
-- 3. Configure cada política abaixo
-- ============================================================================

-- ============================================================================
-- POLÍTICA 1: INSERT (Upload)
-- ============================================================================
-- Nome: "Usuários podem fazer upload de avatares próprios"
-- 
-- Target roles: authenticated
-- Allowed operation: INSERT
-- 
-- Policy definition (USING):
-- (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text)
--
-- Policy definition (WITH CHECK):
-- (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text)
-- ============================================================================

-- ============================================================================
-- POLÍTICA 2: UPDATE (Upsert)
-- ============================================================================
-- Nome: "Usuários podem atualizar avatares próprios"
-- 
-- Target roles: authenticated
-- Allowed operation: UPDATE
-- 
-- Policy definition (USING):
-- (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text)
--
-- Policy definition (WITH CHECK):
-- (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text)
-- ============================================================================

-- ============================================================================
-- POLÍTICA 3: DELETE
-- ============================================================================
-- Nome: "Usuários podem deletar avatares próprios"
-- 
-- Target roles: authenticated
-- Allowed operation: DELETE
-- 
-- Policy definition (USING):
-- (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text)
-- ============================================================================

-- ============================================================================
-- POLÍTICA 4: SELECT (Download/Leitura)
-- ============================================================================
-- Nome: "Avatares são públicos para leitura"
-- 
-- Target roles: public
-- Allowed operation: SELECT
-- 
-- Policy definition (USING):
-- (bucket_id = 'avatars')
-- ============================================================================

-- ============================================================================
-- EXPLICAÇÃO DAS POLÍTICAS
-- ============================================================================
--
-- INSERT/UPDATE/DELETE:
-- - Apenas usuários autenticados podem fazer essas operações
-- - Apenas no diretório próprio: avatars/{user_id}/*
-- - A função storage.foldername(name)[1] extrai o primeiro nível do caminho
--   (que deve ser o user_id)
-- - auth.uid()::text retorna o ID do usuário autenticado como texto
--
-- SELECT:
-- - Qualquer pessoa (incluindo não autenticados) pode ler avatares
-- - Necessário para exibir avatares nas páginas públicas
-- - Não há restrição de diretório (público pode ver todos os avatares)
--
-- ESTRUTURA DE PASTAS ESPERADA:
-- avatars/
--   └── {user_id}/
--       ├── 1234567890-abc123.jpg
--       ├── 1234567891-xyz789.png
--       └── ...
--
-- ============================================================================

